name: Build WSL
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency: build-wsl

env:
  goversion: '1.18'

jobs:
  build-rootfs:
    uses: ./.github/workflows/rootfs.yaml
  build-wsl:
    needs: build-rootfs
    name: Build openEuler ${{ matrix.release }} ${{ matrix.arch }} app
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        release: [22.03, 20.03]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Download artifact
        uses: actions/download-artifact@v2
      - uses: actions/setup-python@v4
        with:
        python-version: '3.11' 
      - name: set env
        shell: bash
        run: |
          if [ "${{ matrix.arch }}" == "x86_64" ];then
            echo "_TARGET=x64" >> $GITHUB_ENV
          else
            echo "_TARGET=ARM64" >> $GITHUB_ENV
          fi
          python3 custom.py -r ${{ matrix.release }}
      - name: show and prepare artifact
        shell: bash
        run: |
          mkdir -p ${{ env._TARGET }}
          mv openeuler-${{ matrix.release }}-${{ matrix.arch }}-wsl-rootfs.tar/openeuler-${{ matrix.release }}-${{ matrix.arch }}-wsl-rootfs.tar.gz ${{ env._TARGET }}/install.tar.gz       
          ls -lh **
      # Decode the Base64 encoded Pfx
      - name: Decode the Pfx
        run: |
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate\certificate.txt -Value '${{ secrets.SIGN_CERT }}'
          certutil -decode certificate\certificate.txt certificate\certificate.pfx
          Import-PfxCertificate -CertStoreLocation Cert:LocalMachine\Trust -FilePath certificate\certificate.pfx
          Import-PfxCertificate -CertStoreLocation Cert:CurrentUser\My -FilePath certificate\certificate.pfx
      - name: Build Bundle
        shell: powershell
        run: |
          msbuild .\DistroLauncher.sln /t:Build /m /nr:false /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="${{ env._TARGET }}" /p:Platform="${{ env._TARGET }}" -verbosity:normal
      - name: Allow downloading sideload appxbundle
        uses: actions/upload-artifact@v2
        with:
          name: sideload-openeuler-${{ matrix.release }}-${{ matrix.arch }}
          path: AppPackages/DistroLauncher-Appx/DistroLauncher-Appx_*/*
          retention-days: 7

