name: Build WSL
on:
  workflow_dispatch:
    inputs:
      appID:
        description: 'Release name to use for the bundle'
        required: true
        default: 'openEulerLatest'
      rootfses:
        description: 'WSL rootfs urls, separated by a colon. Direct set of "tar.gz::arch" if arch is not in the filename'
        required: true
        default: ''
      rootfseschecksum:
        description: 'Should download a SHA256SUMS file to check the rootfs'
        required: true
        default: 'no'
      upload:
        description: 'Should we upload the appxbundle to the store'
        required: true
        default: 'no'
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 10 * * *'
concurrency: build-wsl

env:
  goversion: '1.18'

jobs:
  build-rootfs:
    uses: ./.github/workflows/rootfs.yaml
  build-wsl:
    needs: build-rootfs
    name: Build openEuler 22.03
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.goversion }}
      - name: Setup MSBuild (PATH)
        uses: microsoft/setup-msbuild@v1.0.2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
      -
        name: Load Docker image
        run: |
          docker load --input myimage.tar
          docker image ls -a
      - name: Build Bundle
        shell: powershell
        run:  .\build.bat rel

